class NationalityMapper:
    def __init__(self):
        self.mapping = {
            "Afghan": "Afghanistan",
            "Albanian": "Albania",
            "Algerian": "Algeria",
            "Andorran": "Andorra",
            "Angolan": "Angola",
            "Argentinian": "Argentina",
            "Armenian": "Armenia",
            "Australian": "Australia",
            "Austrian": "Austria",
            "American" : "United States",
            "Azerbaijani": "Azerbaijan",
            "Bahamian": "Bahamas",
            "Bahraini": "Bahrain",
            "Bangladeshi": "Bangladesh",
            "Barbadian": "Barbados",
            "Belarusian": "Belarus",
            "Belgian": "Belgium",
            "Belizean": "Belize",
            "Beninese": "Benin",
            "Bhutanese": "Bhutan",
            "Bolivian": "Bolivia",
            "Bosnian": "Bosnia and Herzegovina",
            "Botswanan": "Botswana",
            "Brazilian": "Brazil",
            "British": "United Kingdom",
            "Bruneian": "Brunei",
            "Bulgarian": "Bulgaria",
            "Burkinabe": "Burkina Faso",
            "Burmese": "Myanmar",
            "Burundian": "Burundi",
            "British" : "United Kingdom",
            "Cambodian": "Cambodia",
            "Cameroonian": "Cameroon",
            "Canadian": "Canada",
            "Cape Verdean": "Cape Verde",
            "Central African": "Central African Republic",
            "Chadian": "Chad",
            "Chilean": "Chile",
            "Chinese": "China",
            "Colombian": "Colombia",
            "Comoran": "Comoros",
            "Congolese": "Democratic Republic of the Congo",
            "Costa Rican": "Costa Rica",
            "Croatian": "Croatia",
            "Cuban": "Cuba",
            "Cypriot": "Cyprus",
            "Czech": "Czech Republic",
            "Danish": "Denmark",
            "Djiboutian": "Djibouti",
            "Dominican": "Dominican Republic",
            "Dutch": "Netherlands",
            "East Timorese": "Timor-Leste",
            "Ecuadorean": "Ecuador",
            "Egyptian": "Egypt",
            "Salvadoran": "El Salvador",
            "Equatorial Guinean": "Equatorial Guinea",
            "Eritrean": "Eritrea",
            "Estonian": "Estonia",
            "Ethiopian": "Ethiopia",
            "Fijian": "Fiji",
            "Finnish": "Finland",
            "French": "France",
            "Gabonese": "Gabon",
            "Gambian": "Gambia",
            "Georgian": "Georgia",
            "German": "Germany",
            "Ghanaian": "Ghana",
            "Greek": "Greece",
            "Grenadian": "Grenada",
            "Guatemalan": "Guatemala",
            "Guinean": "Guinea",
            "Guinea-Bissauan": "Guinea-Bissau",
            "Guyanese": "Guyana",
            "Haitian": "Haiti",
            "Honduran": "Honduras",
            "Hungarian": "Hungary",
            "Icelandic": "Iceland",
            "Indian": "India",
            "Indonesian": "Indonesia",
            "Iranian": "Iran",
            "Iraqi": "Iraq",
            "Irish": "Ireland",
            "Israeli": "Israel",
            "Italian": "Italy",
            "Ivorian": "Ivory Coast",
            "Jamaican": "Jamaica",
            "Japanese": "Japan",
            "Jordanian": "Jordan",
            "Kazakhstani": "Kazakhstan",
            "Kenyan": "Kenya",
            "Kittian and Nevisian": "Saint Kitts and Nevis",
            "Kuwaiti": "Kuwait",
            "Kyrgyz": "Kyrgyzstan",
            "Laotian": "Laos",
            "Latvian": "Latvia",
            "Lebanese": "Lebanon",
            "Liberian": "Liberia",
            "Libyan": "Libya",
            "Liechtensteiner": "Liechtenstein",
            "Lithuanian": "Lithuania",
            "Luxembourger": "Luxembourg",
            "Macedonian": "North Macedonia",
            "Malagasy": "Madagascar",
            "Malawian": "Malawi",
            "Malaysian": "Malaysia",
            "Maldivian": "Maldives",
            "Malian": "Mali",
            "Maltese": "Malta",
            "Marshallese": "Marshall Islands",
            "Mauritanian": "Mauritania",
            "Mauritian": "Mauritius",
            "Mexican": "Mexico",
            "Micronesian": "Micronesia",
            "Moldovan": "Moldova",
            "Monacan": "Monaco",
            "Mongolian": "Mongolia",
            "Moroccan": "Morocco",
            "Mosotho": "Lesotho",
            "Motswana": "Botswana",
            "Mozambican": "Mozambique",
            "Namibian": "Namibia",
            "Nauruan": "Nauru",
            "Nepalese": "Nepal",
            "New Zealander": "New Zealand",
            "Nicaraguan": "Nicaragua",
            "Nigerien": "Niger",
            "Nigerian": "Nigeria",
            "North Korean": "North Korea",
            "Northern Irish": "United Kingdom",
            "Norwegian": "Norway",
            "Omani": "Oman",
            "Pakistani": "Pakistan",
            "Palauan": "Palau",
            "Panamanian": "Panama",
            "Papua New Guinean": "Papua New Guinea",
            "Paraguayan": "Paraguay",
            "Peruvian": "Peru",
            "Filipino": "Philippines",
            "Polish": "Poland",
            "Portuguese": "Portugal",
            "Qatari": "Qatar",
            "Romanian": "Romania",
            "Russian": "Russia",
            "Rwandan": "Rwanda",
            "Saint Lucian": "Saint Lucia",
            "Salvadoran": "El Salvador",
            "Samoan": "Samoa",
            "San Marinese": "San Marino",
            "Sao Tomean": "Sao Tome and Principe",
            "Saudi": "Saudi Arabia",
            "Scottish": "United Kingdom",
            "Senegalese": "Senegal",
            "Serbian": "Serbia",
            "Seychellois": "Seychelles",
            "Sierra Leonean": "Sierra Leone",
            "Singaporean": "Singapore",
            "Slovak": "Slovakia",
            "Slovenian": "Slovenia",
            "Solomon Islander": "Solomon Islands",
            "Somali": "Somalia",
            "South African": "South Africa",
            "South Korean": "South Korea",
            "Spanish": "Spain",
            "Sri Lankan": "Sri Lanka",
            "Sudanese": "Sudan",
            "Surinamer": "Suriname",
            "Swazi": "Eswatini",
            "Swedish": "Sweden",
            "Swiss": "Switzerland",
            "Syrian": "Syria",
            "Taiwanese": "Taiwan",
            "Tajik": "Tajikistan",
            "Tanzanian": "Tanzania",
            "Thai": "Thailand",
            "Togolese": "Togo",
            "Tongan": "Tonga",
            "Trinidadian or Tobagonian": "Trinidad and Tobago",
            "Tunisian": "Tunisia",
            "Turkish": "Turkey",
            "Turkmen": "Turkmenistan",
            "Tuvaluan": "Tuvalu",
            "Ugandan": "Uganda",
            "Ukrainian": "Ukraine",
            "Uruguayan": "Uruguay",
            "Uzbekistani": "Uzbekistan",
            "Venezuelan": "Venezuela",
            "Vietnamese": "Vietnam",
            "Welsh": "United Kingdom",
            "Yemenite": "Yemen",
            "Zambian": "Zambia",
            "Zimbabwean": "Zimbabwe",
        }
        self.known_mappings={
            'Afghanistan': ['Afghanistan'],
            'Albania': ['Albania'],
            'Algeria': ['Algeria'],
            'Andorra': ['Andorra'],
            'Angola': ['Angola'],
            'Antigua and Barbuda': ['Antigua and Barbuda'],
            'Argentina': ['Argentina'],
            'Armenia': ['Armenia'],
            'Australia': ['Australia'],
            'Austria': ['Austria', 'Austria (possibly)'],
            'Azerbaijan': ['Azerbaijan'],
            'Bahamas': ['Bahamas'],
            'Bahrain': ['Bahrain'],
            'Bangladesh': ['Bangladesh'],
            'Barbados': ['Barbados'],
            'Belarus': ['Belarus'],
            'Belgium': ['Belgium'],
            'Belize': ['Belize'],
            'Benin': ['Benin'],
            'Bhutan': ['Bhutan'],
            'Bolivia': ['Bolivia'],
            'Bosnia and Herzegovina': ['Bosnia and Herzegovina'],
            'Botswana': ['Botswana'],
            'Brazil': ['Brazil'],
            'British Isles' : ['British Isles', 'British Islands'],
            'Brunei Darussalam': ['Brunei Darussalam'],
            'Bulgaria': ['Bulgaria'],
            'Burkina Faso': ['Burkina Faso'],
            'Burundi': ['Burundi'],
            'Cabo Verde': ['Cabo Verde'],
            'Cambodia': ['Cambodia'],
            'Cameroon': ['Cameroon'],
            'Canada': ['Canada'],
            'Central African Republic': ['Central African Republic'],
            'Chad': ['Chad'],
            'Chile': ['Chile'],
            'China': ['China'],
            'Colombia': ['Colombia'],
            'Comoros': ['Comoros'],
            'Congo': ['Congo'],
            'Costa Rica': ['Costa Rica'],
            'Croatia': ['Croatia'],
            'Cuba': ['Cuba'],
            'Cyprus': ['Cyprus'],
            'Czech Republic': ['Czech Republic'],
            'North Korea': ['Democratic People\'s Republic of Korea', 'North Korea'],
            'Democratic Republic of the Congo': ['Democratic Republic of the Congo', 'DMR', 'Dem. Rep. Congo'],
            'Denmark': ['Denmark'],
            'Djibouti': ['Djibouti'],
            'Dominica': ['Dominica'],
            'Dominican Republic': ['Dominican Republic'],
            'Ecuador': ['Ecuador'],
            'Egypt': ['Egypt'],
            'El Salvador': ['El Salvador'],
            'Equatorial Guinea': ['Equatorial Guinea'],
            'Eritrea': ['Eritrea'],
            'Estonia': ['Estonia'],
            'Eswatini': ['Eswatini'],
            'Ethiopia': ['Ethiopia'],
            'Fiji': ['Fiji'],
            'Finland': ['Finland'],
            'France': ['France'],
            'Gabon': ['Gabon'],
            'Gambia': ['Gambia'],
            'Georgia': ['Georgia'],
            'Germany': ['Germany'],
            'Ghana': ['Ghana'],
            'Greece': ['Greece'],
            'Grenada': ['Grenada'],
            'Guatemala': ['Guatemala'],
            'Guinea': ['Guinea'],
            'Guinea-Bissau': ['Guinea-Bissau'],
            'Guyana': ['Guyana'],
            'Haiti': ['Haiti'],
            'Honduras': ['Honduras'],
            'Hungary': ['Hungary'],
            'Iceland': ['Iceland'],
            'India': ['India'],
            'Indonesia': ['Indonesia'],
            'Iran': ['Iran (Islamic Republic of)', 'Iran'],
            'Iraq': ['Iraq'],
            'Ireland': ['Ireland'],
            'Israel': ['Israel'],
            'Italy': ['Italy'],
            'Jamaica': ['Jamaica'],
            'Japan': ['Japan'],
            'Jordan': ['Jordan'],
            'Kazakhstan': ['Kazakhstan'],
            'Kenya': ['Kenya'],
            'Kiribati': ['Kiribati'],
            'Kuwait': ['Kuwait'],
            'Kyrgyzstan': ['Kyrgyzstan'],
            'Lao People\'s Democratic Republic': ['Lao People\'s Democratic Republic'],
            'Latvia': ['Latvia'],
            'Lebanon': ['Lebanon'],
            'Lesotho': ['Lesotho'],
            'Liberia': ['Liberia'],
            'Libya': ['Libya'],
            'Liechtenstein': ['Liechtenstein'],
            'Lithuania': ['Lithuania'],
            'Luxembourg': ['Luxembourg'],
            'Madagascar': ['Madagascar'],
            'Malawi': ['Malawi'],
            'Malaysia': ['Malaysia'],
            'Maldives': ['Maldives'],
            'Mali': ['Mali'],
            'Malta': ['Malta'],
            'Marshall Islands': ['Marshall Islands'],
            'Mauritania': ['Mauritania'],
            'Mauritius': ['Mauritius'],
            'Mexico': ['Mexico'],
            'Micronesia': ['Micronesia (Federated States of)', 'Micronesia'],
            'Monaco': ['Monaco'],
            'Mongolia': ['Mongolia'],
            'Montenegro': ['Montenegro'],
            'Morocco': ['Morocco'],
            'Mozambique': ['Mozambique'],
            'Myanmar': ['Myanmar'],
            'Namibia': ['Namibia'],
            'Nauru': ['Nauru'],
            'Nepal': ['Nepal'],
            'Netherlands': ['Netherlands'],
            'New Zealand': ['New Zealand'],
            'Nicaragua': ['Nicaragua'],
            'Niger': ['Niger'],
            'Nigeria': ['Nigeria'],
            'North Macedonia': ['North Macedonia'],
            'Norway': ['Norway'],
            'Oman': ['Oman'],
            'Pakistan': ['Pakistan'],
            'Palau': ['Palau'],
            'Panama': ['Panama'],
            'Papua New Guinea': ['Papua New Guinea'],
            'Paraguay': ['Paraguay'],
            'Peru': ['Peru'],
            'Philippines': ['Philippines'],
            'Poland': ['Poland'],
            'Portugal': ['Portugal'],
            'Qatar': ['Qatar'],
            'Republic of Korea': ['Republic of Korea'],
            'Republic of Moldova': ['Republic of Moldova'],
            'Romania': ['Romania'],
            'Russia': ['Russian Federation', 'Russia'],
            'Rwanda': ['Rwanda'],
            'Saint Kitts and Nevis': ['Saint Kitts and Nevis'],
            'Saint Lucia': ['Saint Lucia'],
            'Saint Vincent and the Grenadines': ['Saint Vincent and the Grenadines'],
            'Samoa': ['Samoa'],
            'San Marino': ['San Marino'],
            'Sao Tome and Principe': ['Sao Tome and Principe'],
            'Saudi Arabia': ['Saudi Arabia'],
            'Senegal': ['Senegal'],
            'Serbia': ['Serbia'],
            'Seychelles': ['Seychelles'],
            'Sierra Leone': ['Sierra Leone'],
            'Singapore': ['Singapore'],
            'Slovakia': ['Slovakia'],
            'Slovenia': ['Slovenia'],
            'Solomon Islands': ['Solomon Islands'],
            'Somalia': ['Somalia'],
            'South Africa': ['South Africa'],
            'South Sudan': ['South Sudan'],
            'Spain': ['Spain'],
            'Sri Lanka': ['Sri Lanka'],
            'Palestine': ['State of Palestine', 'Palestine'],
            'Sudan': ['Sudan'],
            'Suriname': ['Suriname'],
            'Sweden': ['Sweden', 'Scandinavia (possibly Sweden)'],
            'Switzerland': ['Switzerland'],
            'Syrian Arab Republic': ['Syrian Arab Republic'],
            'Tajikistan': ['Tajikistan'],
            'Thailand': ['Thailand'],
            'Timor-Leste': ['Timor-Leste'],
            'Togo': ['Togo'],
            'Tonga': ['Tonga'],
            'Trinidad and Tobago': ['Trinidad and Tobago'],
            'Tunisia': ['Tunisia', 'Tunesia'],
            'Turkey': ['Turkey'],
            'Turkmenistan': ['Turkmenistan'],
            'Tuvalu': ['Tuvalu'],
            'Uganda': ['Uganda'],
            'Ukraine': ['Ukraine'],
            'United Arab Emirates': ['United Arab Emirates'],
            'United Kingdom': ['United Kingdom of Great Britain and Northern Ireland', 'UK', 'United Kingdom'],
            'United Republic of Tanzania': ['United Republic of Tanzania'],
            'United States': ['United States of America', 'USA', 'United States'],
            'Uruguay': ['Uruguay'],
            'Uzbekistan': ['Uzbekistan'],
            'Vanuatu': ['Vanuatu'],
            'Venezuela': ['Venezuela (Bolivarian Republic of)', 'Venezuela'],
            'Vietnam': ['Viet Nam', 'Vietnam'],
            'Yemen': ['Yemen'],
            'Zambia': ['Zambia'],
            'Zimbabwe': ['Zimbabwe'],
            'Unknown': ['Unknown']
        }

    def get_country_by_nationality(self, nationality):
        return self.mapping.get(nationality, "Unknown")
    
    def get_known_mappings(self):
        return self.known_mappings